theme: jekyll-theme-minimal

logo: https://github.com/etaagen/etaagen.github.io/blob/master/images/circle-wheat_smaller.png?raw=true

title: Ellie Taagen 

description:  Genomics | Data Science | Ph.D.

github: is\_project\_page:false  

