theme: jekyll-theme-minimal

logo: https://github.com/etaagen/etaagen.github.io/blob/master/images/circle-wheat.png?raw=true

title: Ella (Ellie) Taagen 

description: Ph.D. student | Plant breeding & genetics | Cornell University   

github:
  is_project_page: false
