theme: jekyll-theme-minimal
title: Ella (Ellie) Taagen  
description: Graduate student studying plant genetics in the Sorrells lab at Cornell University  
  + [Email](et395@cornell.edu)  
  
  + [Twitter](https://twitter.com/etaagen)  
  
  + [GitHub](https://github.com/etaagen)
