theme: jekyll-theme-minimal

logo: https://github.com/etaagen/etaagen.github.io/blob/master/images/circle-wheat.png?raw=true

title: Ella (Ellie) Taagen 

description: PhD candidate | Plant Genetics, Cornell University        

github: is\_project\_page:false  

<html>
  <head>
   <meta name="google-site-verification" content="yul2C6Bauqlyf82t19IepEIDbyPbK5MTF-t0qKOrzqs" />
  </head>
</html>
